<?xml version="1.0"?>
<robot name="mobo_bot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!--  URDF WHEEL WITH RIM -->

    <xacro:property name="w_radius" value="${wheel_radius}"/>
    <xacro:property name="w_width" value="${wheel_width}"/>
    <xacro:property name="w_mass" value="${wheel_mass}"/>
    <xacro:property name="w_color" value="black"/>
    <xacro:property name="rim_color" value="red"/>
    <xacro:property name="rim_spoke_width" value="0.005"/>

    <xacro:macro name="wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${w_radius}" length="${w_width}"/>
            </geometry>
            <material name="${w_color}"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <!-- <cylinder radius="${w_radius}" length="${w_width}"/> -->
                <sphere radius="${w_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${w_mass}" length="${w_width}" radius="${w_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>

    <xacro:macro name="wheel_rim">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${rim_spoke_width} ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <box size="${rim_spoke_width} ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/4}"/>
            <geometry>
                <box size="${rim_spoke_width} ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/4}"/>
            <geometry>
                <box size="${rim_spoke_width} ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
    </xacro:macro>

    <!--  #################################################### -->








    <!--  MESHED WHEEL INSERT -->

    <xacro:macro name="wheel_mesh">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                <!-- <xacro:unless value="${gazebo_visual}">
                    <mesh filename="package://mobo_bot_description/meshes/wheel.stl"/>
                </xacro:unless>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                </xacro:if> -->
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.02"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.4" length="0.02" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>

    <!--  ################################################## -->


    <!-- <link name="left_wheel_link">
        <xacro:insert_mesh_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="left_wheel_link"/> -->
    
</robot>