<?xml version="1.0"?>
<robot name="mobo_bot" xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:macro name="box_with_fillet" params="x y z size_x size_y size_z fillet_radius material">
            <!-- logitudinal box -->
            <visual>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
                <geometry>
                    <box size="${size_x} ${size_y-(2*fillet_radius)} ${size_z}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- lateral box -->
            <visual>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
                <geometry>
                    <box size="${size_x-(2*fillet_radius)} ${size_y} ${size_z}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder1 -->
            <visual>
                <origin xyz="${x+((size_x/2)-fillet_radius)} ${y+((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder2 -->
            <visual>
                <origin xyz="${x+((size_x/2)-fillet_radius)} ${y-((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder3 -->
            <visual>
                <origin xyz="${x-((size_x/2)-fillet_radius)} ${y+((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder4 -->
            <visual>
                <origin xyz="${x-((size_x/2)-fillet_radius)} ${y-((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
    </xacro:macro>



   




    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="wheel_mass" value="0.4"/>
    <xacro:property name="wheel_color" value="black"/>
    <xacro:property name="rim_color" value="red"/>


    <xacro:macro name="insert_drive_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="${wheel_color}"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>


    <xacro:macro name="insert_wheel_rim">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 ${wheel_radius*1.2} ${wheel_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <box size="0.01 ${wheel_radius*1.2} ${wheel_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/4}"/>
            <geometry>
                <box size="0.01 ${wheel_radius*1.2} ${wheel_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/4}"/>
            <geometry>
                <box size="0.01 ${wheel_radius*1.2} ${wheel_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
    </xacro:macro>



    <!-- <joint name="right_wheel_rim_joint" type="fixed">
        <parent link="right_wheel_link"/>
        <child link="right_wheel_rim_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="right_wheel_rim_link">
        <xacro:insert_wheel_rim/>
    </link>

    <gazebo reference="right_wheel_rim_link">
        <material>Gazebo/Red</material>
    </gazebo> -->











     <xacro:macro name="insert_mesh_drive_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                <!-- <xacro:unless value="${gazebo_visual}">
                    <mesh filename="package://mobo_bot_description/meshes/wheel.stl"/>
                </xacro:unless>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                </xacro:if> -->
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.02"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.4" length="0.02" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>


    <!-- <link name="left_wheel_link">
        <xacro:insert_mesh_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="left_wheel_link"/> -->


    
</robot>