<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="other_parts/box_with_fillet_macro.xacro"/>
    <xacro:include filename="other_parts/drive_wheel_macro.xacro"/>
    <xacro:include filename="other_parts/drive_wheel_rim_macro.xacro"/>
    
    <xacro:include filename="sensors/sonar.xacro"/>
    <xacro:include filename="sensors/lidar.xacro"/>
    <xacro:include filename="sensors/imu.xacro"/>
    <!-- <xacro:include filename="sensors/cam.xacro"/> -->


    <xacro:property name="chassis_length" value="0.25"/>
    <xacro:property name="chassis_width" value="0.19"/>
    <xacro:property name="chassis_height" value="0.07"/>
    <xacro:property name="chassis_mass" value="3.0"/>

    <xacro:property name="wheel_seperation" value="0.214"/>
    <xacro:property name="wheel_radius" value="0.034"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.08"/>

    <xacro:property name="castor_wheel_radius" value="0.025"/>
    <xacro:property name="castor_wheel_mass" value="0.04"/>

    






    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_link">  
    </link>

    <!-- ################# -->








    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${(wheel_radius*2)+0.002}"/>
    </joint>

    <link name="chassis">
        <xacro:insert_box_with_fillet x="0" y="0" z="${chassis_height/2}" 
            size_x="${chassis_length}" size_y="${chassis_width}" size_z="${chassis_height}" 
            fillet_radius="0.06" material="orange"/>
        <collision>
           <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!--  ########################### -->










    <!-- FRONT LEFT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="front_left_wheel" 
        parent_name="base_link" 
        x="0.05" y="${wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>
  
    <xacro:insert_drive_wheel_rim
        base_name="front_left_rim" 
        parent_name="front_left_wheel" 
        x="0" y="0" z="0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->




    <!-- REAR LEFT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="rear_left_wheel" 
        parent_name="base_link" 
        x="-0.05" y="${wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>
  
    <xacro:insert_drive_wheel_rim
        base_name="rear_left_rim" 
        parent_name="rear_left_wheel" 
        x="0" y="0" z="0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->





    <!-- FRONT RIGHT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="front_right_wheel" 
        parent_name="base_link" 
        x="0.05" y="${-wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>

    <xacro:insert_drive_wheel_rim
        base_name="front_right_rim" 
        parent_name="front_right_wheel" 
        x="0" y="0" z="-0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->



    <!-- REAR RIGHT DRIVE WHEEL -->

    <xacro:insert_drive_wheel 
        base_name="rear_right_wheel" 
        parent_name="base_link" 
        x="-0.05" y="${-wheel_seperation/2}" z="${wheel_radius}"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"/>

    <xacro:insert_drive_wheel_rim
        base_name="rear_right_rim" 
        parent_name="rear_right_wheel" 
        x="0" y="0" z="-0.001"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################# -->



















    <!--  sonar -->
    <xacro:insert_sonar
        base_name="sonar" 
        parent_name="chassis" 
        x="${chassis_length/2}" y="0" z="${chassis_height/2}"
        mass="0.005"
        min_range="0.02" max_range="3.0"
        resolution="0.01" visualize="false"/>

    
     <!--  lidar -->
    <xacro:property name="lidar_z_offset" value="0.04"/>
    <xacro:insert_lidar 
        base_name="lidar" 
        parent_name="chassis" 
        x="${-chassis_length/6}" y="0" z="${chassis_height+lidar_z_offset}"
        mass="0.1" samples="360"
        min_angle="${-pi*2}" max_angle="${pi*2}"
        min_range="0.1" max_range="10"
        visualize="false"/>

    

    <!--  imu -->
    <xacro:insert_imu
        base_name="imu" 
        parent_name="chassis" 
        x="0" y="0" z="${chassis_height}"/>



    <!-- camera -->
    <!-- <xacro:property name="cam_x_offset" value="0.04"/>
    <xacro:property name="cam_z_offset" value="0.02"/>
    <xacro:insert_camera
        base_name="camera" 
        parent_name="chassis" 
        x="${(chassis_length*0.375)+cam_x_offset}" y="0" z="${chassis_height+cam_z_offset}"
        mass="0.005"
        width="320" height="240"
        min_range="0.02" max_range="5.0"
        tilt_angle="0"
        visualize="true"/> -->



</robot>