<?xml version="1.0"?>
<robot name="mobo_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="other_parts/fillet_box_macro.xacro"/>
    <xacro:include filename="other_parts/insert_drive_wheel_macro.xacro"/>
    <xacro:include filename="other_parts/insert_castor_wheel_macro.xacro"/>

    <xacro:property name="chassis_height" value="0.125"/>
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="wheel_seperation" value="0.3"/>
    <xacro:property name="chassis_mass" value="4.0"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.08"/>
    <xacro:property name="castor_wheel_radius" value="${wheel_radius/2}"/>
    <xacro:property name="castor_wheel_mass" value="0.04"/>
    <xacro:property name="chassis_width" value="${wheel_seperation-wheel_width-0.01}"/>

    





    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_link">  
    </link>

    <!-- ################# -->






    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <link name="chassis">
        <xacro:box_with_fillet x="${-chassis_length/8}" y="0" z="${chassis_height/2}" size_x="${chassis_length}" size_y="${chassis_width}" size_z="${chassis_height}" fillet_radius="0.05" material="orange"/>
        <collision>
           <origin xyz="${-chassis_length/8} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${-chassis_length/8} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!--  ########################### -->






    <xacro:insert_drive_wheel 
        base_name="left_wheel" 
        parent_name="chassis" 
        x="0" y="${wheel_seperation/2}" z="0"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>


    <xacro:insert_drive_wheel 
        base_name="right_wheel" 
        parent_name="chassis" 
        x="0" y="${-wheel_seperation/2}" z="0"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>



    <!--  castor WHEEL LINK -->

    <joint name="castor_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="castor_wheel"/>
        <origin xyz="${-chassis_length/2} 0 ${-wheel_radius/2}"/>
    </joint>


    <link name="castor_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${castor_wheel_mass}" radius="${wheel_radius/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="castor_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <!-- <kp>1000000.0</kp> -->
        <!-- <kd>1.0</kd> -->
        <!-- <fdir1>1 0 0</fdir1> -->
        <!-- <minDepth>0.01</minDepth> -->
        <material>Gazebo/Grey</material>
    </gazebo>

    <!--  ########################### -->

</robot>