<?xml version="1.0"?>
<robot name="mobo_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="other_parts/box_with_fillet_macro.xacro"/>
    <xacro:include filename="other_parts/drive_wheel_macro.xacro"/>
    <xacro:include filename="other_parts/face_macro.xacro"/>
    <xacro:include filename="sensors/lidar.xacro"/>
    <xacro:include filename="sensors/imu.xacro"/>
    <xacro:include filename="sensors/cam.xacro"/>
    <xacro:include filename="sensors/sonar.xacro"/>



    <xacro:property name="chassis_height" value="0.125"/>
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="wheel_seperation" value="0.3"/>
    <xacro:property name="chassis_mass" value="4.0"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.08"/>
    <xacro:property name="castor_wheel_radius" value="${wheel_radius/2}"/>
    <xacro:property name="castor_wheel_mass" value="0.04"/>
    <xacro:property name="chassis_width" value="${wheel_seperation-wheel_width-0.01}"/>

    





    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_link">  
    </link>

    <!-- ################# -->






    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <link name="chassis">
        <xacro:insert_box_with_fillet x="${-chassis_length/8}" y="0" z="${chassis_height/2}" 
            size_x="${chassis_length}" size_y="${chassis_width}" size_z="${chassis_height}" 
            fillet_radius="0.05" material="orange"/>
        <collision>
           <origin xyz="${-chassis_length/8} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${-chassis_length/8} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>


    <xacro:insert_face parent_name="chassis" x="${(chassis_length/8)*3}" y="0" z="${chassis_height/2}"/>

    <!--  ########################### -->






    <!-- LEFT AND RIGHT DRIVE WHEELS -->

    <xacro:insert_drive_wheel 
        base_name="left_wheel" 
        parent_name="chassis" 
        x="0" y="${wheel_seperation/2}" z="0"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>


    <xacro:insert_drive_wheel 
        base_name="right_wheel" 
        parent_name="chassis" 
        x="0" y="${-wheel_seperation/2}" z="0"
        mass="${wheel_mass}"
        radius="${wheel_radius}"
        thickness="${wheel_width}"
        spoke_width="0.005"/>

    <!-- ############################### -->







    <!--  castor WHEEL LINK -->

    <joint name="castor_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="castor_wheel"/>
        <origin xyz="${-chassis_length/2} 0 ${-wheel_radius/2}"/>
    </joint>


    <link name="castor_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <material name="silver"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${castor_wheel_mass}" radius="${wheel_radius/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="castor_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <!-- <kp>1000000.0</kp> -->
        <!-- <kd>1.0</kd> -->
        <!-- <fdir1>1 0 0</fdir1> -->
        <!-- <minDepth>0.01</minDepth> -->
        <material>Gazebo/Silver</material>
    </gazebo>

    <!--  ########################### -->





    <!--  lidar -->
    <xacro:property name="lidar_z_offset" value="0.1"/>
    <xacro:insert_lidar 
        base_name="lidar" 
        parent_name="chassis" 
        x="${-chassis_length/4}" y="0" z="${chassis_height+lidar_z_offset}"
        mass="0.08"/>




    <!--  imu -->
    <xacro:insert_imu
        base_name="imu" 
        parent_name="chassis" 
        x="0" y="0" z="${chassis_height}"/>





    <!--  line tracking camera style -->
    <!-- <xacro:insert_camera
        base_name="line_cam" 
        parent_name="chassis" 
        x="${(chassis_length*0.375)+0.03}" y="0" z="${0.05-wheel_radius}"
        mass="0.005" tilt_angle="${pi/2.1}"/> -->


    <!--  normal camera style -->
    <!-- <xacro:property name="cam_x_offset" value="0.04"/>
    <xacro:property name="cam_z_offset" value="0.02"/>
    <xacro:insert_camera
        base_name="line_cam" 
        parent_name="chassis" 
        x="${(chassis_length*0.375)+cam_x_offset}" y="0" z="${chassis_height+cam_z_offset}"
        mass="0.005" tilt_angle="0"/> -->





    <!--  front sonar sensor -->
    <!-- <xacro:insert_sonar
        base_name="sonar" 
        parent_name="chassis" 
        x="${(chassis_length*0.375)+0.005}" y="0" z="${chassis_height/2}"
        mass="0.0005"/> -->



</robot>