<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="mobo_bot">


    <xacro:include filename="$(find mobo_bot_description)/urdf/color_macros.xacro"/>
    <xacro:include filename="$(find mobo_bot_description)/urdf/part_macros.xacro"/>
    <xacro:include filename="$(find mobo_bot_description)/urdf/inertia_macros.xacro"/>


    <xacro:property name="chassis_height" value="0.15"/>


    <xacro:arg name="laser_visual" default="false"/>
    <xacro:arg name="imu_visual"   default="true"/>
    <xacro:arg name="sonar_visual"   default="false"/>
    <xacro:arg name="cam_visual"   default="false"/>

    



     <!-- GAZEBO WHEEL PARAMETERS -->
    <xacro:macro name="gazebo_wheel_settings" params="name">
        <gazebo reference="${name}">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <!-- <kp>${kp}</kp> -->
            <!-- <kd>${kd}</kd> -->
            <!-- <fdir1>${fdir}</fdir1> -->
            <minDepth>0.01</minDepth>
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>







    <!-- BASE LINK -->

    <!-- <base joint/> -->
    <link name="base_footprint">  
    </link>

    <!-- ################# -->






    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 0.05"/>
    </joint>


    <link name="chassis_link">
        <xacro:box_with_fillet x="-0.05" y="0" z="${chassis_height/2}" size_x="0.4" size_y="0.37" size_z="${chassis_height}" fillet_radius="0.1" material="white"/>
        <collision>
           <origin xyz="-0.05 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="0.4 0.37 ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="5.0" x="0.4" y="0.37" z="${chassis_height}">
            <origin xyz="-0.05 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis_link">
        <material>Gazebo/White</material>
    </gazebo>
    <!--  ########################### -->








    <!--  FRONT LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_footprint"/>
        <child link="left_wheel_link"/>
        <origin xyz="0 0.2 0.05" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

     <link name="left_wheel_link">
        <xacro:insert_mesh_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="left_wheel_link"/>


    <!-- <link name="left_wheel_link">
        <xacro:insert_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="left_wheel_link"/>


    <joint name="left_wheel_rim_joint" type="fixed">
        <parent link="left_wheel_link"/>
        <child link="left_wheel_rim_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="left_wheel_rim_link">
        <xacro:insert_wheel_rim/>
    </link>

    <gazebo reference="left_wheel_rim_link">
        <material>Gazebo/Red</material>
    </gazebo> -->


    <!--  ########################### -->












    <!--  FRONT RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_footprint"/>
        <child link="right_wheel_link"/>
        <origin xyz="0 -0.2 0.05" rpy="${-pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

     <link name="right_wheel_link">
        <xacro:insert_mesh_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="right_wheel_link"/>


    <!-- <link name="right_wheel_link">
        <xacro:insert_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="right_wheel_link"/>


    <joint name="right_wheel_rim_joint" type="fixed">
        <parent link="right_wheel_link"/>
        <child link="right_wheel_rim_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="right_wheel_rim_link">
        <xacro:insert_wheel_rim/>
    </link>

    <gazebo reference="right_wheel_rim_link">
        <material>Gazebo/Red</material>
    </gazebo> -->







    <!--  CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="-0.18 0 0"/>
    </joint>


    <link name="caster_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
           <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.5" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel_link">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <!-- <kp>1000000.0</kp>
        <kd>1.0</kd>
        <fdir1>1 0 0</fdir1> -->
        <minDepth>0.01</minDepth>
        <material>Gazebo/Grey</material>
    </gazebo>

    <!--  ########################### -->









    <xacro:include filename="$(find mobo_bot_description)/urdf/gazebo_controllers.xacro"/>








    <!-- <xacro:include filename="$(find mobo_bot_description)/urdf/sensors/imu.xacro"/> -->
    <xacro:include filename="$(find mobo_bot_description)/urdf/sensors/lidar.xacro"/>
    <xacro:include filename="$(find mobo_bot_description)/urdf/sensors/cam.xacro"/>
    <xacro:include filename="$(find mobo_bot_description)/urdf/sensors/sonar.xacro"/>

  
</robot>